# Generated by Django 3.2.9 on 2021-11-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='a',
        ),
    ]
