# Generated by Django 3.2.9 on 2021-11-30 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '__first__'),
        ('editorial', '__first__'),
        ('category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=150)),
                ('fecha_publicacion', models.DateField()),
                ('descripcion', models.CharField(max_length=250)),
                ('id_editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editorial.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='LibroCategory',
            fields=[
                ('id_libro_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
        migrations.CreateModel(
            name='LibroAutor',
            fields=[
                ('id_libro_autor', models.AutoField(primary_key=True, serialize=False)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
    ]
