# Generated by Django 3.2.9 on 2021-12-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='descripcion',
            field=models.TextField(max_length=8000),
        ),
    ]
