# Generated by Django 3.2.9 on 2021-12-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fecha_publicacion',
            field=models.CharField(max_length=50),
        ),
    ]
